version: "3.9"

services:
  moviewatchlist:
    build: .
    container_name: moviewatchlist
    ports:
      - "5050:5050"
    env_file: .env
    environment:
      PORT: 5050
    volumes:
      - ~/.moviewatchlist_data:/app/instance
    restart: unless-stopped
